modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPL v3, https://www.gnu.org/licenses/gpl-3.0.en.html"
issueTrackerURL="https://github.com/SirBlobman/BlobmansStuff/issues"
[[mods]]
modId="blobmanstuff"
version="${file.jarVersion}"
displayName="Blobman's Stuff"
displayURL="https://www.curseforge.com/minecraft/mc-mods/blobmans-stuff"
logoFile="assets/blobmanstuff/logo.png"
credits="The developers at Mojang and Forge for making this mod possible."
authors="SirBlobman"
description='''
Adds stuff into the game based on the character of SirBlobman.
Includes custom slime balls, blocks, weapons, armor, and mobs.
'''

[[dependencies.blobmanstuff]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.blobmanstuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
